/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "var(--background)",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "surface-container-high": "var(--surface-container-high)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "secondary-fixed": "var(--secondary-fixed)",
        "surface-dim": "var(--surface-dim)",
        "on-surface-variant": "var(--on-surface-variant)",
        "tertiary": "var(--tertiary)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "tertiary-container": "var(--tertiary-container)",
        "secondary-container": "var(--secondary-container)",
        "surface-container-highest": "var(--surface-container-highest)",
        "outline-variant": "var(--outline-variant)",
        "inverse-surface": "var(--inverse-surface)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "surface-variant": "var(--surface-variant)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "on-primary": "var(--on-primary)",
        "outline": "var(--outline)",
        "error-container": "var(--error-container)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "surface-container": "var(--surface-container)",
        "on-tertiary": "var(--on-tertiary)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "primary-container": "var(--primary-container)",
        "surface-tint": "var(--surface-tint)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-primary-container": "var(--on-primary-container)",
        "surface-container-low": "var(--surface-container-low)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "inverse-primary": "var(--inverse-primary)",
        "on-secondary": "var(--on-secondary)",
        "surface": "var(--surface)",
        "secondary": "var(--secondary)",
        "on-surface": "var(--on-surface)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-error-container": "var(--on-error-container)",
        "primary-fixed": "var(--primary-fixed)",
        "surface-bright": "var(--surface-bright)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
