# Local development profile
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drishti_kon
    username: drishti
    password: password

  jpa:
    show-sql: true

logging:
  level:
    com.drishti.kon: DEBUG

app:
  moderators:
    emails:
      - sandeepyadav_230295@aitpune.edu.in
      - souravkushwaha_230290@aitpune.edu.in
      - sahilkumar_230298@aitpune.edu.in
      - maneeshkumar_230287@aitpune.edu.in
